name: Update GH pages
# This workflow is triggered on pushes to the repository.
on: [push]
jobs:
  build:
    # Job name is Greeting
    name: Build and deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.11.x'
      - run: yarn install
      - run: yarn deploy
